INSERT INTO `countries` (`countryCode`, `countryName`, `aciCountry`) VALUES
('KNA', 'St. Kitts and Nevis', 'No'),
('KOR', 'Korea, Rep.', 'No'),
('KWT', 'Kuwait', 'No'),
('LAC', 'Latin America & Caribbean (excluding high income)', 'No'),
('LAO', 'Lao PDR', 'Yes'),
('LBN', 'Lebanon', 'No'),
('LBR', 'Liberia', 'No'),
('LBY', 'Libya', 'No'),
('LCA', 'St. Lucia', 'No'),
('LCN', 'Latin America & Caribbean ', 'No'),
('LDC', 'Least developed countries: UN classification', 'No'),
('LIC', 'Low income', 'No'),
('LIE', 'Liechtenstein', 'No'),
('LKA', 'Sri Lanka', 'No'),
('LMC', 'Lower middle income', 'No'),
('LMY', 'Low & middle income', 'No'),
('LSO', 'Lesotho', 'No'),
('LTE', 'Late-demographic dividend', 'No'),
('LTU', 'Lithuania', 'No'),
('LUX', 'Luxembourg', 'No'),
('LVA', 'Latvia', 'No'),
('MAC', 'Macao SAR, China', 'No'),
('MAF', 'St. Martin (French part)', 'No'),
('MAR', 'Morocco', 'No'),
('MCO', 'Monaco', 'No'),
('MDA', 'Moldova', 'No'),
('MDE', 'Middle East (developing only)', 'No'),
('MDG', 'Madagascar', 'No'),
('MDV', 'Maldives', 'No'),
('MEA', 'Middle East & North Africa', 'No'),
('MEX', 'Mexico', 'No'),
('MHL', 'Marshall Islands', 'No'),
('MIC', 'Middle income', 'No'),
('MKD', 'North Macedonia', 'No'),
('MLI', 'Mali', 'No'),
('MLT', 'Malta', 'No'),
('MMR', 'Myanmar', 'Yes'),
('MNA', 'Middle East & North Africa (excluding high income)', 'No'),
('MNE', 'Montenegro', 'No'),
('MNG', 'Mongolia', 'No'),
('MNP', 'Northern Mariana Islands', 'No'),
('MOZ', 'Mozambique', 'No'),
('MRT', 'Mauritania', 'No'),
('MUS', 'Mauritius', 'No'),
('MWI', 'Malawi', 'No'),
('MYS', 'Malaysia', 'Yes'),
('NAC', 'North America', 'No'),
('NAF', 'North Africa', 'No'),
('NAM', 'Namibia', 'No'),
('NCL', 'New Caledonia', 'No'),
('NER', 'Niger', 'No'),
('NGA', 'Nigeria', 'No'),
('NIC', 'Nicaragua', 'No'),
('NLD', 'Netherlands', 'No'),
('NOR', 'Norway', 'No'),
('NPL', 'Nepal', 'No'),
('NRS', 'Non-resource rich Sub-Saharan Africa countries', 'No'),
('NRU', 'Nauru', 'No'),
('NXS', 'IDA countries not classified as fragile situations, excluding Sub-Saharan Africa', 'No'),
('NZL', 'New Zealand', 'No'),
('OED', 'OECD members', 'No'),
('OMN', 'Oman', 'No'),
('OSS', 'Other small states', 'No'),
('PAK', 'Pakistan', 'No'),
('PAN', 'Panama', 'No'),
('PER', 'Peru', 'No'),
('PHL', 'Philippines', 'Yes'),
('PLW', 'Palau', 'No'),
('PNG', 'Papua New Guinea', 'No'),
('POL', 'Poland', 'No'),
('PRE', 'Pre-demographic dividend', 'No'),
('PRI', 'Puerto Rico', 'No'),
('PRK', 'Korea, Dem. People's Rep.', 'No'),
('PRT', 'Portugal', 'No'),
('PRY', 'Paraguay', 'No'),
('PSE', 'West Bank and Gaza', 'No'),
('PSS', 'Pacific island small states', 'No'),
('PST', 'Post-demographic dividend', 'No'),
('PYF', 'French Polynesia', 'No'),
('QAT', 'Qatar', 'No'),
('ROU', 'Romania', 'No'),
('RRS', 'Resource rich Sub-Saharan Africa countries', 'No'),
('RUS', 'Russian Federation', 'No'),
('RWA', 'Rwanda', 'No'),
('SAS', 'South Asia', 'No'),
('SAU', 'Saudi Arabia', 'No'),
('SDN', 'Sudan', 'No'),
('SEN', 'Senegal', 'No'),
('SGP', 'Singapore', 'Yes'),
('SLB', 'Solomon Islands', 'No'),
('SLE', 'Sierra Leone', 'No'),
('SLV', 'El Salvador', 'No'),
('SMR', 'San Marino', 'No'),
('SOM', 'Somalia', 'No'),
('SRB', 'Serbia', 'No'),
('SSA', 'Sub-Saharan Africa (excluding high income)', 'No'),
('SSD', 'South Sudan', 'No'),
('SSF', 'Sub-Saharan Africa ', 'No'),
('SST', 'Small states', 'No'),
('STP', 'Sao Tome and Principe', 'No'),
('ABW', 'Aruba', 'No'),
('AFE', 'Africa Eastern and Southern', 'No'),
('AFG', 'Afghanistan', 'No'),
('AFR', 'Africa', 'No'),
('AFW', 'Africa Western and Central', 'No'),
('AGO', 'Angola', 'No'),
('ALB', 'Albania', 'No'),
('AND', 'Andorra', 'No'),
('ARB', 'Arab World', 'No'),
('ARE', 'United Arab Emirates', 'No'),
('ARG', 'Argentina', 'No'),
('ARM', 'Armenia', 'No'),
('ASM', 'American Samoa', 'No'),
('ATG', 'Antigua and Barbuda', 'No'),
('AUS', 'Australia', 'No'),
('AUT', 'Austria', 'No'),
('AZE', 'Azerbaijan', 'No'),
('BDI', 'Burundi', 'No'),
('BEA', 'East Asia & Pacific (IBRD-only countries)', 'No'),
('BEC', 'Europe & Central Asia (IBRD-only countries)', 'No'),
('BEL', 'Belgium', 'No'),
('BEN', 'Benin', 'No'),
('BFA', 'Burkina Faso', 'No'),
('BGD', 'Bangladesh', 'No'),
('BGR', 'Bulgaria', 'No'),
('BHI', 'IBRD countries classified as high income', 'No'),
('BHR', 'Bahrain', 'No'),
('BHS', 'Bahamas, The', 'No'),
('BIH', 'Bosnia and Herzegovina', 'No'),
('BLA', 'Latin America & the Caribbean (IBRD-only countries)', 'No'),
('BLR', 'Belarus', 'No'),
('BLZ', 'Belize', 'No'),
('BMN', 'Middle East & North Africa (IBRD-only countries)', 'No'),
('BMU', 'Bermuda', 'No'),
('BOL', 'Bolivia', 'No'),
('BRA', 'Brazil', 'No'),
('BRB', 'Barbados', 'No'),
('BRN', 'Brunei Darussalam', 'Yes'),
('BSS', 'Sub-Saharan Africa (IBRD-only countries)', 'No'),
('BTN', 'Bhutan', 'No'),
('BWA', 'Botswana', 'No'),
('CAA', 'Sub-Saharan Africa (IFC classification)', 'No'),
('CAF', 'Central African Republic', 'No'),
('CAN', 'Canada', 'No'),
('CEA', 'East Asia and the Pacific (IFC classification)', 'No'),
('CEB', 'Central Europe and the Baltics', 'No'),
('CEU', 'Europe and Central Asia (IFC classification)', 'No'),
('CHE', 'Switzerland', 'No'),
('CHI', 'Channel Islands', 'No'),
('CHL', 'Chile', 'No'),
('CHN', 'China', 'Yes'),
('CIV', 'Cote d'Ivoire', 'No'),
('CLA', 'Latin America and the Caribbean (IFC classification)', 'No'),
('CME', 'Middle East and North Africa (IFC classification)', 'No'),
('CMR', 'Cameroon', 'No'),
('COD', 'Congo, Dem. Rep.', 'No'),
('COG', 'Congo, Rep.', 'No'),
('COL', 'Colombia', 'No'),
('COM', 'Comoros', 'No'),
('CPV', 'Cabo Verde', 'No'),
('CRI', 'Costa Rica', 'No'),
('CSA', 'South Asia (IFC classification)', 'No'),
('CSS', 'Caribbean small states', 'No'),
('CUB', 'Cuba', 'No'),
('CUW', 'Curacao', 'No'),
('CYM', 'Cayman Islands', 'No'),
('CYP', 'Cyprus', 'No'),
('CZE', 'Czechia', 'No'),
('DEA', 'East Asia & Pacific (IDA-eligible countries)', 'No'),
('DEC', 'Europe & Central Asia (IDA-eligible countries)', 'No'),
('DEU', 'Germany', 'No'),
('DFS', 'IDA countries classified as Fragile Situations', 'No'),
('DJI', 'Djibouti', 'No'),
('DLA', 'Latin America & the Caribbean (IDA-eligible countries)', 'No'),
('DMA', 'Dominica', 'No'),
('DMN', 'Middle East & North Africa (IDA-eligible countries)', 'No'),
('DNF', 'IDA countries not classified as Fragile Situations', 'No'),
('DNK', 'Denmark', 'No'),
('DNS', 'IDA countries in Sub-Saharan Africa not classified as fragile situations ', 'No'),
('DOM', 'Dominican Republic', 'No'),
('DSA', 'South Asia (IDA-eligible countries)', 'No'),
('DSF', 'IDA countries in Sub-Saharan Africa classified as fragile situations ', 'No'),
('DSS', 'Sub-Saharan Africa (IDA-eligible countries)', 'No'),
('DZA', 'Algeria', 'No'),
('EAP', 'East Asia & Pacific (excluding high income)', 'No'),
('EAR', 'Early-demographic dividend', 'No'),
('EAS', 'East Asia & Pacific', 'No'),
('ECA', 'Europe & Central Asia (excluding high income)', 'No'),
('ECS', 'Europe & Central Asia', 'No'),
('ECU', 'Ecuador', 'No'),
('EGY', 'Egypt, Arab Rep.', 'No'),
('EMU', 'Euro area', 'No'),
('ERI', 'Eritrea', 'No'),
('ESP', 'Spain', 'No'),
('EST', 'Estonia', 'No'),
('ETH', 'Ethiopia', 'No'),
('EUU', 'European Union', 'No'),
('FCS', 'Fragile and conflict affected situations', 'No'),
('FIN', 'Finland', 'No'),
('FJI', 'Fiji', 'No'),
('FRA', 'France', 'No'),
('FRO', 'Faroe Islands', 'No'),
('FSM', 'Micronesia, Fed. Sts.', 'No'),
('FXS', 'IDA countries classified as fragile situations, excluding Sub-Saharan Africa', 'No'),
('GAB', 'Gabon', 'No'),
('GBR', 'United Kingdom', 'No'),
('GEO', 'Georgia', 'No'),
('GHA', 'Ghana', 'No'),
('GIB', 'Gibraltar', 'No'),
('GIN', 'Guinea', 'No'),
('GMB', 'Gambia, The', 'No'),
('GNB', 'Guinea-Bissau', 'No'),
('GNQ', 'Equatorial Guinea', 'No'),
('GRC', 'Greece', 'No'),
('GRD', 'Grenada', 'No'),
('GRL', 'Greenland', 'No'),
('GTM', 'Guatemala', 'No'),
('GUM', 'Guam', 'No'),
('GUY', 'Guyana', 'No'),
('HIC', 'High income', 'No'),
('HKG', 'Hong Kong SAR, China', 'No'),
('HND', 'Honduras', 'No'),
('HPC', 'Heavily indebted poor countries (HIPC)', 'No'),
('HRV', 'Croatia', 'No'),
('HTI', 'Haiti', 'No'),
('HUN', 'Hungary', 'No'),
('IBB', 'IBRD, including blend', 'No'),
('IBD', 'IBRD only', 'No'),
('IBT', 'IDA & IBRD total', 'No'),
('IDA', 'IDA total', 'No'),
('IDB', 'IDA blend', 'No'),
('IDN', 'Indonesia', 'Yes'),
('IDX', 'IDA only', 'No'),
('IMN', 'Isle of Man', 'No'),
('IND', 'India', 'Yes'),
('INX', 'Not classified', 'No'),
('IRL', 'Ireland', 'No'),
('IRN', 'Iran, Islamic Rep.', 'No'),
('IRQ', 'Iraq', 'No'),
('ISL', 'Iceland', 'No'),
('ISR', 'Israel', 'No'),
('ITA', 'Italy', 'No'),
('JAM', 'Jamaica', 'No'),
('JOR', 'Jordan', 'No'),
('JPN', 'Japan', 'No'),
('KAZ', 'Kazakhstan', 'No'),
('KEN', 'Kenya', 'No'),
('KGZ', 'Kyrgyz Republic', 'No'),
('KHM', 'Cambodia', 'Yes'),
('KIR', 'Kiribati', 'No'),
('SUR', 'Suriname', 'No'),
('SVK', 'Slovak Republic', 'No'),
('SVN', 'Slovenia', 'No'),
('SWE', 'Sweden', 'No'),
('SWZ', 'Eswatini', 'No'),
('SXM', 'Sint Maarten (Dutch part)', 'No'),
('SXZ', 'Sub-Saharan Africa excluding South Africa', 'No'),
('SYC', 'Seychelles', 'No'),
('SYR', 'Syrian Arab Republic', 'No'),
('TCA', 'Turks and Caicos Islands', 'No'),
('TCD', 'Chad', 'No'),
('TEA', 'East Asia & Pacific (IDA & IBRD countries)', 'No'),
('TEC', 'Europe & Central Asia (IDA & IBRD countries)', 'No'),
('TGO', 'Togo', 'No'),
('THA', 'Thailand', 'Yes'),
('TJK', 'Tajikistan', 'No'),
('TKM', 'Turkmenistan', 'No'),
('TLA', 'Latin America & the Caribbean (IDA & IBRD countries)', 'No'),
('TLS', 'Timor-Leste', 'No'),
('TMN', 'Middle East & North Africa (IDA & IBRD countries)', 'No'),
('TON', 'Tonga', 'No'),
('TSA', 'South Asia (IDA & IBRD)', 'No'),
('TSS', 'Sub-Saharan Africa (IDA & IBRD countries)', 'No'),
('TTO', 'Trinidad and Tobago', 'No'),
('TUN', 'Tunisia', 'No'),
('TUR', 'Turkiye', 'No'),
('TUV', 'Tuvalu', 'No'),
('TWN', 'Taiwan, China', 'No'),
('TZA', 'Tanzania', 'No'),
('UGA', 'Uganda', 'No'),
('UKR', 'Ukraine', 'No'),
('UMC', 'Upper middle income', 'No'),
('URY', 'Uruguay', 'No'),
('USA', 'United States', 'No'),
('UZB', 'Uzbekistan', 'No'),
('VCT', 'St. Vincent and the Grenadines', 'No'),
('VEN', 'Venezuela, RB', 'No'),
('VGB', 'British Virgin Islands', 'No'),
('VIR', 'Virgin Islands (U.S.)', 'No'),
('VNM', 'Vietnam', 'Yes'),
('VUT', 'Vanuatu', 'No'),
('WLD', 'World', 'No'),
('WSM', 'Samoa', 'No'),
('XKX', 'Kosovo', 'No'),
('XZN', 'Sub-Saharan Africa excluding South Africa and Nigeria', 'No'),
('YEM', 'Yemen, Rep.', 'No'),
('ZAF', 'South Africa', 'No'),
('ZMB', 'Zambia', 'No'),
('ZWE', 'Zimbabwe', 'No');